### ISSUE TITLE
Capturing HDV 1080i with dvgrab 3.5, loss of audio in last frames and additional video frames

### ISSUE THREAD

**Issue by hvdw53** [ddennedy/dvgrab#12]
Hi Dan

Pardon me if I tackle this problem in the wrong way, but I am searching for days now for a solution.

I have  a Sony HDV (HDR-HC1E) video camera. Capturing DV works 100% but HDV 1080i the m2t files don't join seamlessly on the editor (Kdenlive) timeline.

The last frames are missing some audio and have extra video frames so that a smooth joint of files is impossible and also the sync with other streams is out by 4 or more frames.

There must be a lot of these cameras still in use and people who also would like to move to HDV.

I would appreciate if you can give some advice or still better a solution/fix.

Command used: "dvgrab -format hdv -autosplit Hcap-" (adding more buffers don't change anything)

Regards
Henry

**Comment by ddennedy** [comment]
This is the nature of HDV. It is a streaming format MPEG-2 transport stream. Also it is mostly coded in something called open GOP. You can not really expect to append captures and get something seamless. You need to trim them possibly after converting to something more edit friendly. People are not moving to HDV, they have moved away years ago.

**Comment by hvdw53** [comment]
Hi Dan

Thanks for your prompt reply. 

On the information you gave, I searched some more and discovered that Apple transcode the Firewire capture stream to ProRess codecs that solves this file tail synchronization problem. I see that ffmpeg supports ProRess, just need to find the transcode command to test. 

Kdenlive also uses ffmpeg so should be able to import the files to edit. 

Thank you very much for your help, if you have some more info I would appreciate. 

Dvgrab is a great user friendly product. 

Regards
Henry

**Comment by hvdw53** [comment]
Hi Dan

Thanks, you got me in the right direction... just for completeness:

I had 2 choices

- A single video "file"
My choice, I downloaded my video in HDV with "dvgrab -a -s 15000 -Cap-" and ended up with 40 minutes video in a single file (Name: Cap-003.m2t, Size: 8.0 GB (7,952,483,096 bytes)). Kdenlive had no problems putting the file on the timeline.
- transcode the steam while downloading with "dvgrab" (dvgrab output)
Have not tried yet

Regards
Henry
