### ISSUE TITLE
"No audio" suddenly in middle of stream

### ISSUE THREAD

**Issue by ralfbergs** [ddennedy/dvgrab#5]
I was grabbing footage from a tape as follows

`dvgrab --autosplit=15 --timestamp --size 0 --rewind --format dv2 --opendml Florida-`

when dvgrab suddenly output lots of messages

`# no audio`

The resulting output file was corrupt from that point on. When I play it, I hear audio all the time(!), but video stops playing from that point.

**Comment by ddennedy** [comment]
I am not really maintaining dvgrab anymore, but I think you should **not** be using AVI format. That requires creation of a distinct audio track by extracting audio data from the raw DV stream, which is what is used for the AVI video track. Raw DV (no AVI container) is a well-supported format and easy to work with. For example, you can concatenate files. The problem you report is very likely specific to the data received from your device and tape and not easy for someone else to reproduce and debug - meaning, between this and my lack of activity, the bug report will likely never get any resolution.

**Comment by ralfbergs** [comment]
Hi Dan, thanks very much for your response.

I think I have already tried all formats available for MiniDV (i. e. AVI 1/2, raw, QT), and for neither I get "perfect" results.

It is very strange, but I have no clue about Firewire or MiniDV, so I can't tell where the problem may be. Is it data corruption between the cam and the PC, i. e. a buggy Firewire driver? Is it a corrupt cam firmware that cannot reliably read and transmit the data? Is it a bug in dvgrab? Is it maybe even flaky tapes that cause read errors?

Can you give any advice how to track this down? I've even tried it on different platforms (two Ubuntu PCs, i. e. a laptop and a desktop, one MacBook Pro using "iMovie 10.1.4", even Win10 on said laptop using "Movie Maker"), and I cannot reliably capture the tapes.

I should mention that the cam I use to read the tapes is not the one that was used to record the tapes. I originally owned a pretty expensive Canon MVX250i that died only after a few tens of tapes recorded. I had it repaired for quite an amount of money, but it died again shortly after it was repaired, so I decided _not_ to have it repaired again, but bought a used Samsung cam to salvage the old tapes...

**Comment by ddennedy** [comment]
This and the inconsistency in #3 can be any of the reasons you describe above, but it least likely to be a bug in the driver or firmware. One way to investigate is to make two captures - one non-splitting and the other with splitting. Then, around the split points, compare the data you received using a tool such as Kino that shows the DV timecode and date/time.

**Comment by ralfbergs** [comment]
I now replaced the camera by buying a "new" (used) one, and all my issues are gone.

For reference: The "broken" camera that created "truncated" and "corrupt" files was a Samsung VP-D101. The "new" camera that works well is a Canon MVX10i E. The original camera that was used to record the tapes is a Canon MVX250i.
