### ISSUE TITLE
Autoconf files missing

### ISSUE THREAD

**Issue by drankinatty** [ddennedy/dvgrab#9]
Attempting to use bootstrap to invoke autoreconf results in the following:

    ./bootstrap
    autoreconf: 'configure.ac' or 'configure.in' is required

sure enough, there are no autoconf files and no configure provided. If that is intentional, then perhaps a Makefile would suffice.

**Comment by ddennedy** [comment]
configure.ac is in the repository; you must have deleted it. bootstrap executes successfully for me on Ubuntu 18.04 as well as configure.

**Comment by ddennedy** [comment]
P.S. You can get a release tarball with a configure script on SourceForge:
https://sourceforge.net/projects/kino/files/dvgrab/3.5/dvgrab-3.5.tar.gz/download
It is normal to not check generated files into source control.

**Comment by drankinatty** [comment]
Yes, I grabbed the 3.5 tarball and got it there. (shi..!) it was my mkbuilddir script that didn't pick it up. Sorry for the noise.
